### ISSUE TITLE
Outdated Code

### ISSUE THREAD

**Issue by enyachoke** [markoradinovic/Vaadin4Spring-MVP-Sample-SpringSecurity#2]
This example is exacly what I want to achiew but it seems to be out of date the package "import org.vaadin.spring.mvp" does not seem to exist in the latest Vaadin4Spring. Any help or guidance will be appreciated. Thanks in advance.

**Comment by markoradinovic** [comment]
It is my implementation of MVP pattern. You can find it in my github repo.

**Comment by enyachoke** [comment]
Thanks for the help
