### ISSUE TITLE
Missing vaadin4spring dependcies

### ISSUE THREAD

**Issue by swallace21** [markoradinovic/Vaadin4Spring-MVP-Sample-SpringSecurity#3]
Hi excellent work on this project!  I am trying to convert it to run on Wildfly 8 as a war file.  When working with the project, Eclipse is reporting that there are several missing jars such as the EventBus and Security, etc...  I know this project should tie into the mutli mode vaadin4spring project.  However there are no  instructions here or there how to complete that final integration step. 

I know part of this is my own ignorance on working with multi mode maven projects.  Is there a good resource to reference to bridge this gap.

**Comment by reborne** [comment]
Indeed good example how to use it, but as @swallace21 said - there's lack of maven dependency. AFAIK vaadin4spring is a part of Spring Vaadin libriaries... the only thing left - is what exact libraries to use

**Comment by reborne** [comment]
Indeed good example how to use it, but as @swallace21 said - there's lack of maven dependency. AFAIK vaadin4spring is a part of Spring Vaadin libraries... the only thing left - is what exact libraries to use

**Comment by markoradinovic** [comment]
This is very old example. I have work on this before official Vaadin Spring addon was avaliable. Since that time I didn't used Vaadin on my projects. There should be a official way of doing this stuff.

**Comment by swallace21** [comment]
What I did as a personal work around was to extract the cryptography package from Spring Security:

`
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-crypto</artifactId>
            <version>4.1.0.RELEASE</version>
        </dependency>
`

For the code use Boolean match = BCrypt.checkpw(enteredPassword, savedPassword) 

Simple as that. :)  Then rely on Vaadin's Navigator and build in your permissions through their using ViewTypes.  Their Dashboard Demo is a great place to start.  Best of luck!
